// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ExempleSelect: typeof import('./src/components/ExempleSelect.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    IonCubeOutline: typeof import('~icons/ion/cube-outline')['default']
    IonIosSearch: typeof import('~icons/ion/ios-search')['default']
    IonRefreshOutline: typeof import('~icons/ion/refresh-outline')['default']
    IonSearchCircle: typeof import('~icons/ion/search-circle')['default']
    IonSearchOutline: typeof import('~icons/ion/search-outline')['default']
    ModelEx: typeof import('./src/components/ModelEx.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchTv: typeof import('./src/components/SearchTv.vue')['default']
  }
}
